server:
  port: 8082

#mail:
#  external:
#    ip: 192.168.0.1
mail:
  external:
    url: https://ti-timeserver.herokuapp.com/api/v1/email/receiveExternalMail
    key: letMeIn

featureswitch:
  printIp: true
  emailUp: true