server:
  port: 8082

mail:
  external:
    url: ti-timeserver.herokuapp.com
    key: letMeIn
    #    ip: 192.168.0.1

featureswitch:
  printIp: true
  emailUp: true

sendfeatureswitch:
  sendingUp: true